#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
dunst &
picom &
flameshot &
xrandr -r 165 &
sh wallpaper.sh
setxkbmap -layout us,ru -option grp:caps_toggle &
xrandr -s 1440x900
feh --bg-fill $HOME/Изображения/res_wallpapers/catppuccin_space.png

bspc monitor -d 1 2 3 4 5 

bspc config normal_border_color   "#7B68EE"
bspc config focused_border_color  "#4169E1"
bspc config border_width 	      3
bspc config window_gap            10
bspc rule -a '*' state=floating

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocl        true
bspc config focus_follows_pointer true
bspc config pointer_modifier      super
bspc config pointer_modifier      mod1
